@startuml
'https://plantuml.com/class-diagram

abstract class CalculadoraAbstracta {
     - operacions: List<Operacio>
     + constructor()
     {abstract} + add(String, Int, Int)
     {abstract} + add(Operacio)
     {abstract} + executar (Int) : Int
}

class Operacio {
    + constructor(String, Int, Int)
    }


CalculadoraAbstracta <|-- Calculadora
CalculadoraAbstracta *-right- Operacio
@enduml